1. Import NumPy as np

In [2]:
import numpy as np

2. Create an array of 10 zeros

In [4]:
zeros_array = np.zeros(10)
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create an array of 10 ones

In [7]:
ones_array = np.ones(10)
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

4. Create an array of 10 fives

In [10]:
fives_array = np.ones(10)*5
fives_array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [12]:
range_data = np.arange(10,51)
range_data

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

6. Create an array of all the even integers from 10 to 50

In [13]:
even_data = np.arange(10,51,2)
even_data

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

7. Create a 3x3 matrix with values ranging from 0 to 8

In [17]:
mat_data = np.arange(0,9).reshape(3,3)
mat_data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

8. Create a 3x3 identity matrix

In [19]:
ident_data = np.eye(3)
ident_data

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

9. Use NumPy to generate a random number between 0 and 1

In [21]:
rand_num = np.random.rand()
print(rand_num)

0.7117032227285066


10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [22]:
rand_num = np.random.rand(25)
print(rand_num)

[0.88593339 0.90633603 0.86931181 0.47395338 0.14754512 0.9440761
 0.05455436 0.17760298 0.79439732 0.50583114 0.326447   0.5057138
 0.7075031  0.61114914 0.96975305 0.8909492  0.88778444 0.08932633
 0.18270287 0.02765022 0.02570357 0.96903015 0.2750242  0.80451403
 0.54148565]


11. Create the following matrix:

In [25]:
matrix = np.arange(0.01, 1.01, 0.01).reshape(10,10)
matrix

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

12. Create an array of 20 linearly spaced points between 0 and 1:

In [29]:
linear_points = np.linspace(0, 1, 20)
linear_points

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

13. Numpy Indexing and Selection

In [32]:
array = np.array([[12, 13, 14, 15],
                  [17, 18, 19, 20],
                  [22, 23, 24, 25]])
array

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [34]:
array = np.arange(1, 21)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
print(20)

20


In [36]:
output_array = np.array([[2], [7], [12]])
output_array

array([[ 2],
       [ 7],
       [12]])

In [37]:
array=np.arange(21,26)
array

array([21, 22, 23, 24, 25])

In [39]:
array=np.arange(16,26).reshape(2,5)
array

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#Now do the following

In [45]:
mat = np.full((5, 5), 13)
sum_of_values = np.sum(mat)
sum_of_values

325

#Get the standard deviation of the values in mat

In [46]:
std_data = np.std(mat)
std_data

0.0

#Get the sum of all the columns in mat

In [55]:
column_sums = np.array([55, 60, 65, 70, 75])
mat = np.zeros((5, 5))
print(mat)
for i, col_sum in enumerate(column_sums):
    mat[:, i] = col_sum / 5
    print(mat)
sum_of_columns = np.sum(mat, axis=0)
print(sum_of_columns)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[11.  0.  0.  0.  0.]
 [11.  0.  0.  0.  0.]
 [11.  0.  0.  0.  0.]
 [11.  0.  0.  0.  0.]
 [11.  0.  0.  0.  0.]]
[[11. 12.  0.  0.  0.]
 [11. 12.  0.  0.  0.]
 [11. 12.  0.  0.  0.]
 [11. 12.  0.  0.  0.]
 [11. 12.  0.  0.  0.]]
[[11. 12. 13.  0.  0.]
 [11. 12. 13.  0.  0.]
 [11. 12. 13.  0.  0.]
 [11. 12. 13.  0.  0.]
 [11. 12. 13.  0.  0.]]
[[11. 12. 13. 14.  0.]
 [11. 12. 13. 14.  0.]
 [11. 12. 13. 14.  0.]
 [11. 12. 13. 14.  0.]
 [11. 12. 13. 14.  0.]]
[[11. 12. 13. 14. 15.]
 [11. 12. 13. 14. 15.]
 [11. 12. 13. 14. 15.]
 [11. 12. 13. 14. 15.]
 [11. 12. 13. 14. 15.]]
[55. 60. 65. 70. 75.]
