In [2]:
# 1) import numpy library as np:
import numpy as np

In [4]:
#2) Convert the given list to a numpy array:
lst = [1,2,3,4,5]
arr =np.array(lst)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
#3) Create an array with five 1's:
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [11]:
#4)  Create an array of size 2x3 with 1's (2 rows, 3 columns) and assign it to a variable:
import numpy as np
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
#4a) Using the variable you have created, change the data type of the array to int:
print(arr)
print("*"*15)
conv_int = np.ones((2,3), dtype='i')
print(conv_int)
#or
print("*"*15)
conv_int1 = arr.astype('i')
print(conv_int1)



[[1. 1. 1.]
 [1. 1. 1.]]
***************
[[1 1 1]
 [1 1 1]]
***************
[[1 1 1]
 [1 1 1]]


In [60]:
#5) Create an array of size 3x3 with 4's on the diagonal:
print(arr)
print("#"*15)
arr_3x3 = np.diag([4,4,4])
print(arr_3x3)
print("#"*15)
arr = np.eye(3)
arr = arr * 4
arr = arr.astype('i')
print(arr)

[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]
###############
[[4 0 0]
 [0 4 0]
 [0 0 4]]
###############
[[4 0 0]
 [0 4 0]
 [0 0 4]]


In [18]:
#6) Create an array from 0 upto 10 (10 not included):
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
#6a) Create an array in range from 12 to 26 using every second number:
arr = np.arange(12,26,2)
print(arr)

[12 14 16 18 20 22 24]


In [21]:
#7) create an array between 2 and 4 with 8 equal spaces:
arr = np.arange(2, 4.01, 0.25)
print(arr)
print("$"*15)
arr1 = np.linspace(2, 4, 8)
print(arr1)

[2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.  ]
$$$$$$$$$$$$$$$
[2.         2.28571429 2.57142857 2.85714286 3.14285714 3.42857143
 3.71428571 4.        ]


In [25]:
#8) import random module from numpy as rd
import numpy.random as rd

In [28]:
#9) Create a random array of 5 elements:
random_arr = np.random.rand(5)
print(random_arr)

[0.51724461 0.72406174 0.58714194 0.83383378 0.69201356]


In [61]:
#10) Create a random array of size 3x5 with values between 0-10:
rand_data = np.random.randint(0,10,size=(3,5))
print(rand_data)

3


In [41]:
#11) take square of the array we have just created in no. 10:
print(rand_data)
print("@"*15)
print(np.square(rand_data))


[[8 0 6 0 3]
 [9 3 5 3 4]
 [1 4 2 7 5]]
@@@@@@@@@@@@@@@
[[64  0 36  0  9]
 [81  9 25  9 16]
 [ 1 16  4 49 25]]


In [46]:
#Create a copy of the array using the last three values of the given array.
#change the first value of the array with 99.
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
print(arr)
print("$"*15)
last_three = arr[-3:]
print(last_three)
print("$"*15)
last_three[0] = 99
print(last_three)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
$$$$$$$$$$$$$$$
[12 13 14]
$$$$$$$$$$$$$$$
[99 13 14]


In [52]:
#Create the below arr_2D array using the arange() function:
arr = np.arange(25)
new_arr = arr.reshape((5,5))
print(new_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [58]:
#Get the array below using indexing:
des_arr = new_arr[1:3, 2:]
print(des_arr)

[[ 7  8  9]
 [12 13 14]]
